## Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in sklearn.datasets.

In [13]:
from sklearn.datasets import load_iris
dataset=load_iris()

In [14]:
print(dataset.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [15]:
X=dataset.data
y=dataset.target

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [17]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [18]:
y_pred=classifier.predict(X_test)

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[15  0  0]
 [ 0 11  0]
 [ 0  0 12]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        11
           2       1.00      1.00      1.00        12

    accuracy                           1.00        38
   macro avg       1.00      1.00      1.00        38
weighted avg       1.00      1.00      1.00        38



Here we are getting 100% accuracy 

## Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.

 becouse of the load_boston dataset has been removed from sklearn.dataset i am creating my own dataset

In [20]:

from sklearn.datasets import make_regression
X1,y1=make_regression(n_samples=1500,n_features=3,n_informative=2,random_state=21)

In [21]:
## segregating train and test data
X_train1,X_test1,y_train1,y_test1=train_test_split(X1,y1,test_size=0.25,random_state=42)

In [22]:
from sklearn.neighbors import KNeighborsRegressor
regressor=KNeighborsRegressor()

In [23]:
regressor.fit(X_train1,y_train1)
y_pred1=regressor.predict(X_test1)

In [24]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error
print(r2_score(y_pred1,y_test1))
print(mean_squared_error(y_pred1,y_test1))
print(mean_absolute_error(y_pred1,y_test1))

0.980765871784502
53.94732159614251
5.240641528552322


## Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using cross-validation on load_iris dataset in sklearn.datasets.

In [25]:
from sklearn.model_selection import GridSearchCV
params={'n_neighbors':[i for i in range(5,10)]}
grid=GridSearchCV(KNeighborsClassifier(),param_grid=params,cv=5,refit=True,verbose=3)
grid.fit(X_train,y_train)
grid.best_params_

Fitting 5 folds for each of 5 candidates, totalling 25 fits
[CV 1/5] END .....................n_neighbors=5;, score=0.957 total time=   0.0s
[CV 2/5] END .....................n_neighbors=5;, score=1.000 total time=   0.0s
[CV 3/5] END .....................n_neighbors=5;, score=0.818 total time=   0.0s
[CV 4/5] END .....................n_neighbors=5;, score=1.000 total time=   0.0s
[CV 5/5] END .....................n_neighbors=5;, score=0.955 total time=   0.0s
[CV 1/5] END .....................n_neighbors=6;, score=0.913 total time=   0.0s
[CV 2/5] END .....................n_neighbors=6;, score=0.957 total time=   0.0s
[CV 3/5] END .....................n_neighbors=6;, score=0.955 total time=   0.0s
[CV 4/5] END .....................n_neighbors=6;, score=1.000 total time=   0.0s
[CV 5/5] END .....................n_neighbors=6;, score=0.955 total time=   0.0s
[CV 1/5] END .....................n_neighbors=7;, score=0.957 total time=   0.0s
[CV 2/5] END .....................n_neighbors=7;,

{'n_neighbors': 6}

## Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in sklearn.datasets.

In [26]:
from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
X_train1_scaled=scalar.fit_transform(X_train1)
X_test1_scaled=scalar.transform(X_test1)
regressor1=KNeighborsRegressor()
regressor1.fit(X_train1_scaled,y_train1)
y_pred1=regressor1.predict(X_test1_scaled)
print(r2_score(y_pred1,y_test1))
print(mean_squared_error(y_pred1,y_test1))
print(mean_absolute_error(y_pred1,y_test1))

0.9825192716622365
49.2606777273997
5.023726111516373


## Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on load_iris dataset in sklearn.datasets.

In [28]:
dataset=load_iris()
X_train,X_test,y_train,y_test=train_test_split(dataset.data,dataset.target,test_size=0.1,random_state=3)
KNClassifier=KNeighborsClassifier(weights='distance')
KNClassifier.fit(X_train,y_train)
y_pred=KNClassifier.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[7 0 0]
 [0 5 0]
 [0 0 3]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         7
           1       1.00      1.00      1.00         5
           2       1.00      1.00      1.00         3

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



## Q6. Implement a function to standardise the features before applying KNN classifier.

In [29]:
from sklearn.preprocessing import StandardScaler

def scale_data(X_train,X_test):
    scaler=StandardScaler()
    X_train=scaler.fit_transform(X_train)
    X_test=scaler.transform(X_test)
    return X_train,X_test

## Q7. Write a Python function to calculate the euclidean distance between two points.

In [37]:
import numpy as np
def distance(p1,p2):
    x1,y1=p1
    x2,y2=p2
    
    x=x2-x1
    y=y2-y1
    
    dist=np.sqrt((x**2)+(y**2))
    return dist
        

In [38]:
distance([2,3],[3,4])

1.4142135623730951

## Q8. Write a Python function to calculate the manhattan distance between two points.

In [39]:
def manhattan_dist(p1,p2):
    x1,y1=p1
    x2,y2=p2
    
    x=abs(x2-x1)
    y=abs(y2-y1)
    
    return x+y

In [40]:
manhattan_dist([2,3],[3,4])

2